### ISSUE TITLE
エラーページ

### ISSUE THREAD

**Issue by seiyab** [seiyab/dijkstra-web#10]
例外が発生した時、「エラーが発生しました」と出る

個々の例外ごとのページは後回しで、一旦共通エラーページだけ作成

**Comment by ukohank517** [comment]
error.html
っていい？

**Comment by seiyab** [comment]
命名規則程度なら作ってくれればレビューします
まあerror.htmlでいいと思います
ちょっとタスクの内容を書かなすぎたのでまとめます

**Comment by ukohank517** [comment]
いえいえ、これでも十分です。

**Comment by seiyab** [comment]
じゃあ一旦任せます。

**Comment by ukohank517** [comment]
#18 対応
