### ISSUE TITLE
アルゴリズム一覧をAPIから取得して表示

### ISSUE THREAD

**Issue by seiyab** [seiyab/dijkstra-web#16]
https://github.com/seiyab/dijkstra-web/issues/15 でAPIからhtmlへのバインドをやるので参考にしてください

開発環境で動作するようにしてください

localはどっちでもいいです。

**Comment by ukohank517** [comment]
#15 を参考しながらやります。

**Comment by seiyab** [comment]
https://github.com/seiyab/dijkstra-api/issues/4
API側がまだできていないので注意

**Comment by seiyab** [comment]
localだけ作成でも可

**Comment by seiyab** [comment]
https://github.com/seiyab/dijkstra-web/pull/19 で作ったページに飛ぶようにアルゴリズムごとのURLでalgorithm_idパラメータを渡してください

**Comment by seiyab** [comment]
https://github.com/seiyab/dijkstra-api/pull/17

**Comment by seiyab** [comment]
@ukohank517 
いつできそうとか見通しある？
