### ISSUE TITLE
/task_serp 問題の表示

### ISSUE THREAD

**Issue by seiyab** [seiyab/dijkstra-web#20]
コンテスト名と問題が離れてて読みづらいのを直したい
<img width="1047" alt="screen shot 2018-01-01 at 16 07 02" src="https://user-images.githubusercontent.com/20365512/34466162-db88bece-ef0d-11e7-8c79-c4dea6cf3e7d.png">
2カラムで難しかったら1カラムにしてもよさそう

**Comment by cabbage63** [comment]
Bootstrapは列の幅を中の文字数に応じてよしなにやってくれているみたい。
改善するなら
- CSSのメディアクエリで画面横幅が広い場合の列幅比率をfixする（25:75とかに）
- 空の列を2つくらい作ってごまかす
あたりかと思うけど、2個目は文書構造が内容と乖離しちゃうので1個目の方向がいいかも。

**Comment by cabbage63** [comment]
#23 プルリク送りました
