### ISSUE TITLE
APIのモックを作る

### ISSUE THREAD

**Issue by seiyab** [seiyab/dijkstra-web#3]
ローカル環境で動作確認するためのモックをつくる

#5 につながることを意識しつつ

**Comment by ukohank517** [comment]
assignedします

**Comment by seiyab** [comment]
assignされるには何か設定がいるのか・・・
Collaboratorに入れてみたけどこれでいけるかな？

**Comment by ukohank517** [comment]
これで大丈夫です！
学習しながらやるんで、一応様子見ながら三日ください。
木曜に何かを報告します。

**Comment by seiyab** [comment]
今更だけど、作る際は、
* APIから取得するオブジェクトの定義をmodelパッケージに
* APIから値を取得するためにコントローラーから呼び出すのにつかうロジックをserviceパッケージに
実装してください。現状のパッケージ構造がおかしければ直しといてww

ざっと調べたところ、RestTemplateからモックの値を取り出すのは難しそうなので、「プロファイルがlocalのときだけ読み込まれて、適当なオブジェクトを作って返すserviceクラス」を作ることになるかなーと思います（RestTemplateを使わない）。
https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-profiles.html
この方法はあまり綺麗ではないので、いい方法があったらコメントでも、プルリクでも提案してください！

**Comment by ukohank517** [comment]
なんか、通常のjavaにで、webアプリ制作の時、entity.model.requestの３つのクラスに分けて書いてたような気がする。

**Comment by seiyab** [comment]
使い分けがきになる

**Comment by seiyab** [comment]
参考 http://www.baeldung.com/rest-template

**Comment by ukohank517** [comment]
すまん、もう閉じたけど、このブランチは消したほうがいいでしょうか？
