### ISSUE TITLE
問題からアルゴリズムを検索

### ISSUE THREAD

**Issue by seiyab** [seiyab/dijkstra-web#44]
@ukohank517 が言ってたやつですがちょっと自分には用途がわからない・・・
画面を考える前にどういう用途で使ってどう便利か練りたい

このチケットは昨日の用途が分かり次第Closeして実装に関しては別でissueを開く

**Comment by ukohank517** [comment]
言ってた張本人でしたが、
でも確かにあたらめて考えると、用途が分かリませんね。

「問題→アルゴリズム」を検索と言っても、
結局その回の解答の部分にアクセスすれば答えに書いてありますし、
付加価値が思いつきませんでした。

**Comment by seiyab** [comment]
まじか
クローズしていいならクローズしてー
